version: "3.8"
services:
  pdf-pipeline:
    build: .
    image: pdf-pipeline:latest
    container_name: pdf-pipeline
    volumes:
      # Mount your Collections (read-only)
      - ./Collections:/app/Collections:ro
      # Persist outputs back to host
      - ./outputs:/app/outputs
      # (Optional) If you skipped downloading model in Dockerfile, mount your local models:
      # - ./models:/app/models:ro
    environment:
      # If you need to override defaults (e.g. collections path):
      - COLLECTIONS_DIR=Collections
    command: ["python3", "main.py", "--mode", "batch", "--collections-dir", "${COLLECTIONS_DIR}"]